// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyApp.Data;

#nullable disable

namespace SurveyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901080653_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SurveyApp.Models.ResponseOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurveyResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteOptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoteOptionId");

                    b.HasIndex("SurveyResponseId", "VoteOptionId")
                        .IsUnique();

                    b.ToTable("ResponseOptions");
                });

            modelBuilder.Entity("SurveyApp.Models.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoteOptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoteOptionId");

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("SurveyApp.Models.VoteOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VoteOptions");
                });

            modelBuilder.Entity("SurveyApp.Models.ResponseOption", b =>
                {
                    b.HasOne("SurveyApp.Models.SurveyResponse", "SurveyResponse")
                        .WithMany("ResponseOptions")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyApp.Models.VoteOption", "VoteOption")
                        .WithMany()
                        .HasForeignKey("VoteOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyResponse");

                    b.Navigation("VoteOption");
                });

            modelBuilder.Entity("SurveyApp.Models.SurveyResponse", b =>
                {
                    b.HasOne("SurveyApp.Models.VoteOption", null)
                        .WithMany("SurveyResponses")
                        .HasForeignKey("VoteOptionId");
                });

            modelBuilder.Entity("SurveyApp.Models.SurveyResponse", b =>
                {
                    b.Navigation("ResponseOptions");
                });

            modelBuilder.Entity("SurveyApp.Models.VoteOption", b =>
                {
                    b.Navigation("SurveyResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
